#just_l0fe is high black basketball player with big black cock in his ass

# Хуйня для подсказок о культурах

hints:
  format: "<br><color:#c0ff21>[Подсказка]</color>: %hint% <click:run_command:'/hints off'><hover:show_text:'Это подсказка для обучения фишкам нашего сервера. Нажмите, чтобы отключить их.'><dark_gray>[Что это?]</dark_gray></hover></click><br>"
  list:
    crops: "Вы так же можете собирать культуры <u><bold>собрать</bold></u> нажав [<key:key.use>] по любой культуре!"
    snow: "Любите снежки? Нажмите [<key:key.sneak> + <key:key.use>] пустой рукой и слепите пару снежков."
    discounts: "Жители на нашем сервере не предоставляют скидок за их излечение"
    fletching: "Нажав [<key:key.sneak> + <key:key.use>] вы можете подписать предмет своим ником! <gradient:#756AB6:#AC87C5><click:open_url:https://wiki.modoru.fun/wiki/subscriptions><hover:show_text:'Переход на стрницу вики'>[с Sub/Sub+]</gradient>"
    brewery: "На нашем сервере есть плагин на бутлегерство....[<key:key.use>] <click:open_url:https://wiki.modoru.fun/custom/brew>сюда, чтобы узнать более.</click>"